### ISSUE TITLE
roles

### ISSUE THREAD

**Issue by ahdinosaur** [valueflows/agent#1]
in my opinion, one major selling point of holodex is a system to describe and delegate roles within a network. a great example of an existing system with similar aims is [GlassFrog](https://glassfrog.holacracy.org/organizations/5).

the concept of a role is overloaded, so in order to architect a beautiful system we need to break it down into its constituent pieces. i'll approach this with a simple example of an actual role: as the "Desk Collector" in [Enspiral Craftworks](http://craftworks.enspiral.com), i have the responsibilities of "every month, collect intention to contribute money to collective desk account, then check people have actually put money into desk account (friendly nags if necessary)". this role organically grew into being last month as we needed to collectively pay-what-we-want for our desks at [Enspiral Space](http://enspiralspace.co.nz) and i volunteered to be the touch point, which in the process lead me to define the role into something beyond me than can be passed on from person to person within Enspiral Craftworks.

we have our first piece to describe roles already which we are calling relationships, namely a connection between multiple agents optionally under the context of other agents. examples of these relationships so far include group <-> member, parent <-> child, steward <-> stewardee, friendships, mentor <-> mentee, followers, customer <-> supplier, etc. as of now, it fails to denote a mechanism for including better information concerning the role played by a given relationship, namely the purpose, domains, responsibilities, etc. we could add this to our `RelationshipType` definition, but i wonder if maybe we are using an inadaquate term, or maybe i'm conflating relationships (aka associations) with another concept.

another piece of the puzzle is combining multiple ["roles"](http://www.w3.org/TR/vocab-org/#org:Role) into a single ["post"](http://www.w3.org/TR/vocab-org/#class-post) that exists independently of the person filing the "roles". the "Desk Collector" in Enspiral Craftworks is one such "post", where we pass it along from person to person while the core "role" stays the same. it's not enough to pass along a single relationship because it's entirely possible that one "post" may contain multiple "roles". the solution for this i've considered is to follow the practice of other concepts in the [Value Network vocabulary](https://github.com/openvocab/ovn) and create a virtual entity that parallels the actual entity, namely a virtual agent entity that parallels actual agent entities. in this way, actual agents (me) can assume many virtual agents ("Desk Collector"), much in the same way that i can put on many hats, masks, coats, etc depending on the situation and context. i'm partial to this virtual parallel because then in many ways we can treat these virtual agents the same as actual agents, which feels right.

i'm gonna think more about this, in particular i think there may be something to virtual agents in combination with capacities instead of relationships, e.g. "the Desk Collector has these capacities (responsibilities described) and depends on these capacities (being an Enspiral Craftworks member)", but i need to iron out some more examples in data format.

/cc @bhaugen @fosterlynn

**Comment by simontegg** [comment]
@ahdinosaur and I talked about this and I realised we already had a good description of roles and responsibilities for **[Loomio Coop](http://loomio.org) members**:

> **Roles & Responsibilities**
> Creating and maintaining the culture of the Loomio co-op
> Set the strategic direction, organisational purpose, vision and values
> Mandate and hold to account the 90-day planning process, deliverables and coordination
> Participate in organisational decision-making online and in meetings
> Attend monthly meetings (physically or remotely) if possible, or figure out a way of keeping up to date otherwise
> Keep up to date with the coordinators’ weekly and monthly reports, and Board meeting notes as time permits
> Keep up to date with financials, and understanding the risks and opportunities involved in decision-making
> Attend 90-day planning sessions and Loomio retreats where possible
> 
> **Organisational involvement**
> Appointing Board members, and approving their pay rate
> The membership can adopt, alter, or revoke any part of the constitution by special resolution
> Vetting and approving new co-op members (make recommendations to the Board)
> Participating in the Loomio stewardship system
> Approving major transactions
> Approving an amalgamation of the coop
> Appointing a liquidator
> Approving Board recommendations on issuing new shares or making a distribution to shareholding members
> Members can give 10 days written notice to the Board of a matter they want raised at the next Board meeting.

**Comment by bhaugen** [comment]
Yeah, roles are really overloaded. Almost as bad as projects and events.

Here are some different concepts that could be called roles from the descriptions above:
1. What an agent does, for example "every month, collect intention to contribute money to collective desk account, then check people have actually put money into desk account".
2. An ongoing relationship between agents, for example, Mikey is the  "Desk Collector" in relationship to Enspiral Craftworks.
3. A post (a relationship with a set of responsibilities that could be performed by more than one agent at different times).
Those are all subtly different and require different implementations.

For example, in our model, (1) the work that somebody does is an Economic Event. The type of work (e.g. "Collecting Money") is an attribute of the event, in our case a ResourceType.

We automatically create an AgentResourceType when somebody does some work for the first time, and keep score of how many hours they spend doing it (so Mikey would have the AgentResourceType [Mikey: Collecting Money].) Or somebody could create that AgentResourceType upfront. The AgentResourceType says that Mikey can do, and has done, Collecting Money.

(2) An ongoing relationship between agents might be almost exactly as stated above, Mikey has the relationship Desk Collector for Enspiral Craftworks.

(3). A Post could be the instantiation of that relationship as a persistent feature of Enspiral Craftworks, so when Mikey is not doing it, somebody else would step in. (Lynn is skeptical about this: in our software, relationships require both agents, and we would just inactivate the [Mikey:Desk Collector:Craftworks] relationship. For a Post, the agent holding the post could be temporarily vacant and Mikey could be replaced by Simon or somebody else.)

(I'm not saying you need to do it the way we did it, but you will probably need to implement all of those concepts one way or another. You might not need them all right away: (1) is only necessary if you want to record the fact that Mikey did that work, for example.)

**Comment by fosterlynn** [comment]
@ahdinosaur very interesting.  I also want to think more about your "virtual agent" and "post" concepts.  Right now it seems to me that the RelationshipType, the Post, and the Virtual Agent could be the same thing.  But possibly not quite, so a bit of thinking out loud:  

A post could imply an actual ongoing position, for example Craftworks might decide to have 2 Desk Collectors, and then that would be 2 Posts, each referring to the RelationshipType Desk Collector. 

I believe the notion of being able to use an Agent and a Virtual Agent (role or position) interchangeably has some history in the REA model.  In a corporate setting, you might just want to record the agent role or position that did something instead of the person themselves.  Like Warehouse Clerk received some resources, rather than Fred received some resources.  We don't do that in NRP - people want complete transparency and accountability, as well as people get credit for work contributions so need to be named.  I'd be interested in what actual examples or use cases you run into in Enspiral-land.  And the model might be a bit tricky but interesting.

**Comment by bhaugen** [comment]
I think Post is missing from the Agent, Relationship (between two agents), and RelationshipType. (I'm using Post here instead Role, but I think the concept at least similar to schema.org::Role (but see also below...)
http://blog.schema.org/2014/06/introducing-role.html
http://schema.org/Role
1. Post will exist in some organizational contexts but not others. For example, Craftworks has a Desk Collector, but Sensorica does not. In other words, Post needs a link to a context Agent.
2. Post may have no holding Agents, or more than one holding Agent. If Mikey stops being the Desk Collector, the Post remains, but is open until somebody else fills it.
3. Post may have additional attributes, e.g. responsibilities, which are probably describable in terms of ProcessTypes and work InputTypes and maybe also work ResourceTypes. (Trying not to introduce unnecessary new objects...).
4. I am not sure how Post connects to Relationship and Relationship Type.
5. One of Enspiral's requirements is to state the start and end dates of Relationships. The same will apply to the holding of a Post by and Agent (however that is represented, whether by a Relationship or something else). 
6. schema.org::Role has startDate and endDate, which appear to apply to an Agent performing a Role. So a Role for schema.org is not the same as a Post, because it does not appear to be independent of the Agent performing it. So it does not seems to be able to represent more than one person playing the same Role, nor a Role which is empty (not performed by anybody at a particular time). 

(I could be wrong about schema.org::Role; they are often a bit ambiguous.)

**Comment by fosterlynn** [comment]
Couple notes to add on to @bhaugen above: Looking at the org:Organization model, they also have Role and Post.  http://www.w3.org/TR/vocab-org/#overview-of-ontology

Post is defined as the generic post that lives beyond people who fill the Post.  But it also has a relationship with the Agent(s) who holds the post at a point in time - I guess the relationship is "instantiated" too?  (called org:holds and org:heldBy - interestingly, split into the 2 directions)

Role is defined like our RelationshipType (no dates), except that it is only between a Person and an Organization, not flexibly between 2 Agents.

Note: I agree that the Post concept is missing from our models.  (And @ahdinosaur note that when I said I thought why not put the "job description" in the RelationshipType, that looks to be not so good - would be better in a Post, as it might depend on the organization.  I'm sure you already thought of that.)

**Comment by fosterlynn** [comment]
More discussion and questions as I think about this.... ongoing, not trying to be definitive.  :)

@ahdinosaur can you give a couple examples of where you think a Post has many Roles/RelationshipTypes?

The way I think of our current RelationshipType is more at the level of a Post than anything like the list @simontegg gave for roles and responsibilities, although there may be other differences between RelationshipType and Post.  (See issue #2 for examples)  Simon's list seems to me like a detailed description of a Post or Role/RelationshipType, which could be factored out as a collection or could be a description field.  This seems like the GlassFrog's accountabilities.  (Nice UI btw!)

The way I think of our Type of Work (a ResourceType) is more like a skill, for when you need to differentiate that for people committing to a task, pricing for value equation, or just for analysis.  So a set of skills vs a set of responsibilities.  Although I admit this is kind of fuzzy, and maybe there is a missing relationship there.  But for now, I think we can leave this out of the discussion to simplify? 

Question:  Would a Post be something where 1 Post could have more than one person assigned at a time?  Or does a Post imply one (or zero) persons assigned at a time and an organization might have more than one Post with the same responsibilities or role?

By our developing terms (not theirs), looks like in GlassFrog each colored circle is a Post, filled by one (or zero) person.  Where 2 Posts have the same name (like Secretary), they have the same description, indicating a Role defined separately and related to the Post.  Don't know what they do if they have more than one Post of the same Role within the same circle.

I'm trying to draw a model including Post, but it's not ready for showing yet even to stimulate discussion.  Maybe yet today.

I'm not sure where to go with Virtual Agent.  It might be that both and Agent and something else that is post-like can be EconomicAgents as they act in Events, etc.  Although I'm a bit nervous about that, and am not sure we have an actual use case among us.  Or is this more of a naming question, guiding how we think about it?

**Comment by fosterlynn** [comment]
OK a tentative attempt:  I don't really like it, can't seem to simplify the slightly different requirements for Post and relationships not defined by the organization.  Anyhow, hopefully food for discussion.
THIS IS OLD, SEE BELOW.
![agent](https://cloud.githubusercontent.com/assets/3776081/6620117/ebf2d316-c89c-11e4-9bdc-be9ad390980f.png)

**Comment by fosterlynn** [comment]
Here is draft 2, I like it better, although I'm sure it can be improved.
![agent](https://cloud.githubusercontent.com/assets/3776081/6654078/8ed97870-ca7b-11e4-99f9-5ea67a876855.png)

I flipped the thought process from starting with our model and adding the context agent to starting with the context agent defining some roles, then those roles get filled.  I put the post (position) into the role so groups that want to define positions can do it right there when everyone is defining roles.  

Interestingly, the way I got my head around to that was @bhaugen and I spent some time this afternoon looking into models from people who were involved in doing analysis patterns back in the day.  This was a brief period coming off the big push on design patterns.  (I'm kind of sad thinking of all the quality modeling work that was done that hasn't been brought forward into the semantic web vocabs.)  Here are a couple interesting snippets from that investigation.
![fowler_party](https://cloud.githubusercontent.com/assets/3776081/6631219/7a0abdf0-c8f0-11e4-89fa-6180bc9ebf1d.png)
@ahdinosaur the above from Martin Fowler is interesting, I think it speaks to your virtual agent?
![odell_agent](https://cloud.githubusercontent.com/assets/3776081/6631227/9168d180-c8f0-11e4-8894-46aa99d565ce.png)
The above is from James Odell.  This is what got me thinking the other direction.  I like the term Position better than Post.  This doesn't maintain the role fulfillment history, which I think we need to do.  It also doesn't support relationships between 2 persons.  But I think his aggregation of roles is like Mikey's parent?  And he does such careful definitions, I find it really good food for thought.

**Comment by ahdinosaur** [comment]
wow @fosterlynn this is amazing, thanks. :)

**Comment by bhaugen** [comment]
@ahdinosaur - followup question about "virtual agents". You wrote, "to follow the practice of other concepts in the Value Network vocabulary and create a virtual entity that parallels the actual entity".

Do you mean a type object (e.g. like AgentType, ResourceType, ProcessType, etc.)? Or something else?

**Comment by fosterlynn** [comment]
I'm wondering if we want the symmetric construct on the type level.  I get it on the relationship level where people need to affirm their end of it.  But on the type level, it seems like the whole thing needs to get defined together, no matter who is defining it.  Thoughts?  We'd need to make sure the relationship could figure out which direction of the type it is referring to.

**Comment by ahdinosaur** [comment]
@bhaugen i mean plans vs actuals, so Commitments vs EconomicEvents.

**Comment by ahdinosaur** [comment]
@fosterlynn what do you use to make those diagrams? i have a new approach for how to model the data (see the [Craftworks](http://craftworks.enspiral.com) data in the new format [here](https://github.com/holodex/app/tree/new-relationship-types/data)) and am keen to make a diagram to help describe it.

in summary, we got rid of the `is` and `has` directionality where we had an object for each direction, now a single relationship object connects multiple roles (no directionality). it seems to be more adaptable than before, and it's giving me ideas on how to connect relationships, roles, agents, and posts.

some rough schemas in lieu of diagrams (making some of this up as i go):

``` yaml
Agent:
  name: 'string'
  relationships: ['Relationship']
  roles: ['Role']
  posts: ['Post']

Post (extends Agent):

RoleType:
  name: 'string'
  pluralName: 'string'
  description: 'string'
  label: 'string'
  dependencies: ['RoleType']
  isContextual: 'boolean'

RelationshipType:
  name: 'string'
  pluralName: 'string'
  roles: ['RoleType']

Role:
  type: 'RoleType'
  agent: 'Agent'

Relationship:
  type: 'RelationshipType'
  roles: ['Role']
```

a work in progress for sure, but an interesting path that came about during a pair programming session with @s01us and @joshuavial. :smile_cat:

**Comment by fosterlynn** [comment]
@ahdinosaur There are a bunch of diagramming tools out there, but I am using cacoo (https://cacoo.com/) at the moment.  It is working well for me. You get 25 free sheets, which I am going through very slowly - warning, they count deleted ones.  I'm using the UML stencil section, but there are lots of choices.  Export to image costs, so I just do alt-print-screen and crop it in paint or gimp.  :)

And awesome to get your responses, I will study with great interest!!

**Comment by fosterlynn** [comment]
@ahdinosaur   @s01us  @joshuavial   Nice.  So far I think I like your normalizing the roles out of the relationship (and types), or putting the relationship part back together, whichever it was.  Might support unidirectional relationships like "follower" better, although there is a distinction between not needing consent and saying the role doesn't exist - people count their followers all the time. :)   Are you thinking to constrain it to 2 maximum roles for a relationship?  How does isContextual work?  Does that in some way take the place of is/has for relationships in situations where there is a kind of "center" implied in the type of relationship?  Some examples on that would be great.  Also don't understand the RoleType dependencies?

My only concern at the moment is that you split Relationship out in the first place to support a LOD situation where it wasn't necessarily clear where the relationship itself should live, or at least you might always have to go get it.  We (and I think you) are working right now with a central data store, so (speaking for myself) I at least tend to think in a traditional normalized mental model.  Will this work well for the open vocab?  (I don't have enough experience in decentralized data to answer the question.)

**Comment by bhaugen** [comment]
Another question:

When I look at [enspiral-craftworks](https://github.com/holodex/app/blob/new-relationship-types/data/groups/enspiral-craftworks.yml), I see all the members and contributors, including "ayumi-member-enspiral-craftworks". When I look at [ayumi](https://github.com/holodex/app/blob/new-relationship-types/data/people/ayumi.yml), I also see "ayumi-member-enspiral-craftworks".

However I also see "ayumi-steward-mix", but when I look at [mix](https://github.com/holodex/app/blob/new-relationship-types/data/people/mix.yml), I don't see ayumi-steward-mix or mix-stewardee-ayumi.

Is this on purpose or accidental? If on purpose, why the difference?

**Comment by ahdinosaur** [comment]
@bhaugen on accident. in the future, the list of relationships for each agent will be populated from all relationships that reference that agent in any role.

**Comment by ahdinosaur** [comment]
@fosterlynn 

yeah, `isContextual` and `dependencies` were ideas i had afterwards. for example, a stewardship relationship has three roles: steward, stewardee, and group. in the group role, `isContextual` is true. in the steward role, `dependencies` is `['stewardee']`. in the stewardee role, `dependencies` is `['steward']`.

about where the data lives, we're thinking that each agent has a copy of the relationship which they both sign similar to http://opencreds.org.

**Comment by ahdinosaur** [comment]
the reason for `isContextual` is to describe certain role types as having different characteristics. other characteristics i can think of are 'source' and 'target', which are characteristics for directional roles (follower is 'source' and followee is 'target, it's possible steward and stewardee are this way too). maybe instead of a boolean flag for characteristics, we should have a property with enumerated possible values.

**Comment by fosterlynn** [comment]
@ahdinosaur 

Dependencies:  Still thinking, and will see where you go on your picture too.

isContextual: I like having an enumerated property too.  We attempted that originally with a behavior code for child, member, customer, etc.  But I took it out of the vocab, some of the list wasn't correct.  I think the way you are thinking about it is closer - maybe we can distill some behaviors given the use cases we know about.  I'm pretty sure we need something since the relationship types are completely user defined.

**Comment by ahdinosaur** [comment]
hmm, if we consider the original Desk Collector role presented to start this issue, it's a standalone role (not really part of either a relationship but i guess could be part of a post) that is within the context of a group. likewise, the stewardship relationship is also within the context of a group. maybe instead of making a separate role to describe context groups (which doesn't really work with standalone roles), we add a context property to RoleType and RelationshipType.

with this, here's where we're at:

![holomodel1](https://cloud.githubusercontent.com/assets/719605/6659064/2b7983ee-cbe1-11e4-96bc-289b6bb53bd0.png)

``` yaml
Agent:
  name: 'string'
  relationships: ['Relationship']
  roles: ['Role']
  posts: ['Post']

Post (extends Agent):

RoleType:
  name: 'string'
  pluralName: 'string'
  description: 'string'
  label: 'string'
  dependencies: ['RoleType']
  context: 'Agent'

RelationshipType:
  name: 'string'
  pluralName: 'string'
  roles: ['RoleType']
  context: 'Agent'

Role:
  type: 'RoleType'
  agent: 'Agent'

Relationship:
  type: 'RelationshipType'
  status: ('active' | 'inactive')
  roles: ['Role']
```

**Comment by ahdinosaur** [comment]
also thanks @fosterlynn for helping me with the diagram. :smiley:

**Comment by fosterlynn** [comment]
@ahdinosaur A few thoughts, but it's getting late so I might not be coherent.  :)  And you're very welcome. :)

If the RelationshipType has a context agent, then the RoleType shouldn't need one because it is the same one?  And in fact it would be the same one on the Relationship/Role level too, right?

(I'm not actually sure RelationshipType should have a context agent, although I was the one who put it there originally, so Post definitions could be there.  Do we want generic RelationshipTypes or do we want the context agent to define and own its own?  Or maybe we could have the best of both worlds by having agents adopt generic RelationshipTypes.  A many to many.  Or just move it down to the Relationship level. ??) 

So in the Desk Collector example, I think of the 2 agents involved in the dependency as say Mikey and Craftworks.  Craftworks is also the context agent, so I see how you think of it.  I need to think more on this one.

**Comment by fosterlynn** [comment]
@ahdinosaur  Here's one riffing off of your latest.....
![agent2](https://cloud.githubusercontent.com/assets/3776081/6695498/ad9c7f10-ccaf-11e4-9fa6-0cef2976f841.png)

**Comment by ahdinosaur** [comment]
from [another comment i just made](https://github.com/open-app/holodex/issues/78#issuecomment-129640292),

> i've been starting to think that roles are really relationships with the context agent. instead of 'Alice is a collaborator in Acme', it might be better as 'Alice collaborates with Acme'. how this relates is that it might be worth ditching roles altogether and just focusing on relationships

**Comment by ahdinosaur** [comment]
new vocab draft using only `Agent`, `AgentType`, `Relationship`, and `RelationshipType`:

![holodex-vocab](https://cloud.githubusercontent.com/assets/719605/9295890/97a93ed8-44d1-11e5-8a39-b093be3dece9.jpg)

(for reference, [previous vocab](https://github.com/open-app/holodex/issues/70#issuecomment-120225030))

**Comment by fosterlynn** [comment]
@ahdinosaur Sweet!  We can get back on generating some data as soon as we can.  We do have a couple other things going on with deadlines, so we'll piece it in asap.

**Comment by gcassel** [comment]
I really like the diagram you posted here on Aug 16, @ahdinosaur .  How do you feel about it now?

_Warning: the rest of this comment is really dense with abstract concepts, related in ways I haven't precisely described before.  So I sure hope it makes sense._

I believe Mikey you were suggesting AgentType as one's relationship with (or role in) a process or system?  Can it be assumed that an Agent may have more than one AgentType?  

I'm bearing in mind that the only role of some Agents, in a given system, may be to benefit by using that system.   So maybe systems could have an AgentType such as 'User' which _every_ permitted user has, and that could often be the _only_ AgentType which some Agents have?

That could also be broken down by multi-agent systems which happen to be community models.... for instance, 'users' could be guests, contributors, members or trustees.  

I can't follow whatever became of the discussion of role vs. Post earlier in this thread.  (Maybe I'm not taking enough time to focus, or to follow links.)    I like the idea of "Position" as an AgentType which includes personal responsibility for one or more functions (or roles) within a system.  Looking a bit deeper, one can say that any of those 'one or more functions (or roles)' _could_ be an AgentType unto itself in complex communities.   Additionally, one AgentType may be to non-coercively facilitate or coordinate the collective activity (a collective function) of one or more other AgentTypes.   

Additionally, I think it's perfectly feasible and sometimes quite desirable for positions--i.e., AgentTypes with one or more listed responsibilities-- to be shared by two or more people, who may informally pass tasks back and forth via effective communications and documentation.

**Comment by ahdinosaur** [comment]
> I really like the diagram you posted here on Aug 16, @ahdinosaur . How do you feel about it now?

yep, haven't had any ground-breaking ideas since.

> I believe Mikey you were suggesting AgentType as one's relationship with (or role in) a process or system? Can it be assumed that an Agent may have more than one AgentType?

i imagined Agents having only one AgenType, though like ResourceType, ProcessType, etc we could find a way to model them as [composable traits](https://en.wikipedia.org/wiki/Trait_%28computer_programming%29).

> I can't follow whatever became of the discussion of role vs. Post earlier in this thread.

what became of role is that i realized all roles, positions, posts, responsibilities, accountabilities, etc are actually just relationships within a group context. so i think you're onto something if you try to reframe your ideas and questions with Relationship and RelationshipType instead of AgentType. :smiley:

**Comment by fosterlynn** [comment]
> I really like the diagram you posted here on Aug 16, @ahdinosaur . How do you feel about it now?

@gcassel that picture is pretty much what the current Agent vocab represents.  We are using subclasses of Agent instead of Agent Types, just a different pattern for the same concept to fit more with LOD think.  The properties are somewhat different, and the naming is cleaned up. Oh, and we split relationships into their two sides or directions, again a LOD driven thing.  But still that is the basic model.  I like it too!

If this doesn't seem right to you, yell....

**Comment by gcassel** [comment]
So an Agent (person _or_ group) can have a specific Relationship of a complex/ multi-part RelationshipType which bundles two or more RelationshipTypes together-- and this should cover personal positions/posts?   

AgentType can effectively focus on all multi-agent groups which are defined by Agents who are practically/ostensibly equal peers, within a given context?

Does that sound about right @fosterlynn and @ahdinosaur ?

**Comment by fosterlynn** [comment]
@gcassel Hmmm.  So there aren't really multi-part relationship types, but agents can have as many relationships of whatever type they need.

We don't really have Post/Position covered, in the sense that we don't have something that lives by itself without the actual relationship between 2 agents.  Can add if/when someone needs it.

Agent type doesn't have anything to do with the relationship, it is just Person or Group - or any other type needed by people using the vocab.  For example, everyone using NRP also uses Organization and Network.  Enspiral has Community, Pod, etc.  The tricky part is that the agent type shouldn't imply a role.  Roles are represented by the agent relationship type, which is implemented as sub-properties of rdf:Property.  A role is always in relation to another agent.

Not totally sure I understood you, so keep asking if I missed it....

**Comment by gcassel** [comment]
@fosterlynn hopefully my new comment in the other thread clarifies the confusion I had last night, when I was (I think) oversimplifying a potential way to describe collective Agents.  Your comment here made lots of sense on that front; thanks.  

Here's another try at what I meant in the other part of my last comment above.   I was thinking that any post/position which included more than one distinct function (such as a responsibility, and/or associated permissions) could be described by fractally expanding the relationship element, potentially showing a list of relationships which are bundled together in that role-- each of which could be modeled (and clickable) to whatever degree that a particular group would want to model them.

Does that make sense?

**Comment by bhaugen** [comment]
@gcassel - it might help if you described some examples of what you are thinking about. They might be relationships between agents (maybe between an individual and a group), they might be responsibilities for resources, or they might be demonstrated skills, they might be commitments to processes, or they might be something we don't have in the vocab yet.

**Comment by bhaugen** [comment]
Re permissions, "accounts", and related stuff: I think we need to consider two main "architectures" for the value flows model and vocab:
- interop between existing apps, and
- "native" VF apps.

I think for interop between existing apps, permissions and accounts are up to them.

For native VF apps, there won't be any accounts or users or logins. You'll be operating from your personal agent, which will have relationships with other agents, including membership relationships with group agents. I have no idea how permissions will work in such environments.

As I wrote [in 1997](http://www.jeffsutherland.org/oopsla97/haugen.html), a lot of artifacts that people think were given by nature or something are just relics of a particular stage of development, like diapers. Maybe there won't be any systems as we see them today. Maybe just the World Wide Web. 

(Or maybe it will all come crashing down in an ecological disaster...or maybe the next human social-economic system will be the much worse alternative instead of the much better...)

**Comment by fosterlynn** [comment]
> I was thinking that any post/position which included more than one distinct function (such as a responsibility, and/or associated permissions) could be described by fractally expanding the relationship element, potentially showing a list of relationships which are bundled together in that role

@gcassel that certainly could be a good model.  I'd like to wait on that until we have someone who wants posts/positions, and then we can make it work for something real.  We in NRP don't have a use case yet.  There almost was one in Holodex, but it has disappeared I think.

**Comment by gcassel** [comment]
Thanks @fosterlynn for the perspective, and I agree on waiting for specific use cases.  I may have some myself soon for roles which require prerequisite roles.  (For instance, a trustee who must be a member.)   

By the way, I used the post/position language before, but would it seem reasonable to _only_ use the term 'role' even for special or unique positions at a given level of organization?     In a generic vocabulary, which of course specific groups could translate however they wish internally...

(That makes me think of one of my other back burner projects--  per-community collaboratively built thesauri...)

**Comment by fosterlynn** [comment]
> By the way, I used the post/position language before, but would it seem reasonable to only use the term 'role' even for special or unique positions at a given level of organization?

I think "role" might be confusing in this context, as it doesn't necessarily imply something that persists without someone in it.....  but of course open for future discussion......

> I may have some myself soon for roles which require prerequisite roles

cool!

**Comment by almereyda** [comment]
We have moved the ValueFlows organization from GitHub to https://lab.allmende.io/valueflows.

This issue has been closed here, and all further discussion on this issue can be done at

> https://lab.allmende.io/valueflows/agent/-/issues/1.

If you have not done so, you are very welcome to register at https://lab.allmende.io and join the ValueFlows organization there.
