### ISSUE TITLE
Let's think about implementing this

### ISSUE THREAD

**Issue by fosterlynn** [valueflows/agent#16]
We can't do this quite yet, but let's start to let our minds wander to the future....  thinking out loud....

Once we get a tentative definition of the vocab for agents and their relationships, let's try an implementation.  What if we could graph the links of the people and groups involved in the open vocab efforts to start?  So looking at people in Enspiral, Mikorizal, PLP, Pixel Humaine, TransforMap, ....... also maybe others who have participated in the ovn vocab discussions, like Brent, Apostolis, Joseph C-D, MetaCurrency, zippy, .....  I'm sure there are more......

What if we had a UI where you could just follow the tracks through linked people and organizations?  Is Henry Story working on something like this?  Would holodex be a start for something like this?

People wouldn't necessarily have to all implement themselves decentralized; we could set up an instance of NRP (or Pixel Humaine or whatever) to house agents and relationships for those who don't want to write software.  We'd need at least a couple separate apps though.....

Predecessors:
1. Agree on proposed vocab for agent in this venue.
2. Get some comments from whoever will be involved, timebox this.  (We should also put it in front of W3C, but I don't think we can wait for anything official to come back.  Might get useful comments though.) 
3. Incorporate comments as needed.

So, let's not wait for perfection, but move forward with something that we like well enough....

**Comment by bhaugen** [comment]
Dogf00d!

**Comment by fosterlynn** [comment]
Copying the following from #15 where I put it by mistake.

In either case, we will need to decide what existing vocab(s) we want to tie in with. @elf-pavlik can help a lot on this, he is more in tune with the state of existing vocabs. See #9 (comment), and the comment right after.

I think we need:
Agent, Person, Organization

Might want Group? Instead of Organization or as a looser variant of Organization?

I do have a question on how to approach this. What do we do with something like foaf:Agent, where the properties are off in another universe, basically related to an agent's online life rather than its agency in economic activity, for example? Why did ActivityStreams create a new Person and Organization? But they reference foaf and others in their context.... ? And I know there was a lot of discussion in the W3C social interest group that @elf-pavlik and I participate in.

So I want to make a reasonable decision, but also don't want to take forever. I assume we can adjust as things change.

@elf-pavlik replied:

:+1: VCard, FOAF, Org, Schema.org (for now picking whatever works from any of them and than participating in process of clarifying such choices with Social IG and Web Schemas groups.

Let's keep in mind possible future data migrations and further aliments via constructs like http://schema.org/supersededBy . I if you can't quickly find any satisfying match in existing vocabs, just create a new terms and stay ready to eventually supersede it with some more common term. See also: https://lists.w3.org/Archives/Public/public-socialweb/2015Aug/0099.html

I understand that we don't need any more AgentType (rdfs:Class) or agentType (rdf:Propery)? Making sub classes of foaf:Agent (or as:Actor) and using rdf:type (@type in JSON-LD) directly should cover all needed cases for his.

For 'RelationshipType' I can create page similar to Verbs owl:Class vs. rdf:Property and we can discuss it further having clear diagrams and while deciding taking into accounts modeling of direct relations , qualified relations and containers.

**Comment by elf-pavlik** [comment]
> Once we get a tentative definition of the vocab for agents and their relationships, let's try an implementation. What if we could graph the links of the people and groups involved in the open vocab efforts to start? So looking at people in Enspiral, Mikorizal, PLP, Pixel Humaine, TransforMap, ....... also maybe others who have participated in the ovn vocab discussions, like Brent, Apostolis, Joseph C-D, MetaCurrency, zippy, ..... I'm sure there are more......

I will participate with my personal profile on _wwelves.org_ and organizational + events on _hackers4peace.net_

> What if we had a UI where you could just follow the tracks through linked people and organizations? Is Henry Story working on something like this? Would holodex be a start for something like this?

We need various UIs which can fetch data from all those web resources. I would propose staring with 3
- http://holodex.enspiral.com/ @ahdinosaur 
- http://metamap.ouishare.net/ @poietic @Connoropolous @Bortseb
- https://data.openoil.net/ @jmatsushita + http://influencemapping.org/

I believe @almereyda could help with deploying all the forks/branches in which we work on convergence on supported data structures.

**Comment by Connoropolous** [comment]
Speaking for myself, I'm excited to see that this conversation is happening, and will be happy to participate. @Bortseb and I have been working on a tool that integrates with slack and collects data programmatically from reactions, and we have been thinking of using it as a foundation for building a few different apps that serve different network self-documenting efforts. So that could include collecting info about relationships. Basically using Slack within our networks as a UI ;)

**Comment by elf-pavlik** [comment]
@Connoropolous sounds interesting? Could you please add some details about what kind of relationships between agents you plan to express? https://github.com/openvocab/agent/wiki/Relationships

When it comes to _reactions_ you may like to take a quick look at ActivityStreams 2.0 drafts
- http://www.w3.org/TR/activitystreams-core/
- http://www.w3.org/TR/activitystreams-vocabulary/

**Comment by Connoropolous** [comment]
@elf-pavlik we don't have anything specific yet, but we've been following along with the data structure being used in the enspiral-data repository and keeping it flexible enough to be able to work with that

**Comment by fosterlynn** [comment]
@Connoropolous sounds interesting, looking forward to it!

**Comment by ahdinosaur** [comment]
@simontegg and i are keen to implement this via Holodex, as it's what we're already doing (or at least intend to do). :smile_cat:

**Comment by fosterlynn** [comment]
This is on its way, closing.....
