### ISSUE TITLE
Name for the vocabulary

### ISSUE THREAD

**Issue by fosterlynn** [valueflows/agent#22]
We will need a name for the vocab.  I'm thinking one name for the whole effort, not just agent, even though I know I am at that level in the issues.  

So, what is the scope?  And what is a good name for that scope?

How about Collaborative Economic Networks?

**Comment by fosterlynn** [comment]
ping @almereyda @oceatoon @acorbi

**Comment by ahdinosaur** [comment]
throwing :spaghetti: at the wall
- network social economics (`nse`)
- social network economy (`sne`)
- network socio-economics (`nse`)
- network planning and accounting (`npa`)
- resource, event, agent (`rea`)
- network flow streams (`nfs`)
- open value network (`ovn`)
- organizing system (`os`)
- network agent economy (`nae`)
- network agent (`na`)
- socio-economic agent (`sea`)
- social economy agents (`sea` )
- social economy activity (`sea`)
- network economy activity (`nea`)
- social economy streams (`ses`)
- network economy streams (`nes`)
- value network streams (`vns`)
- network ecosystem streams (`nes`)
- social ecosystem streams (`ses`)

**Comment by ahdinosaur** [comment]
i see the scope as being "abstract data streams to define, plan, and account networked socio-economic systems" or "abstract data streams for organizing socio-economic agents".

**Comment by fosterlynn** [comment]
from @bhaugen : social economic ecosystems ==> "see"

**Comment by almereyda** [comment]
I feel personally delighted having been raised here. Citing @fosterlynn:

> If nothing else, it looks to be an interesting ride.
- `sss` swarm stream stack
- `sen` socio-economic networking
- `npr` networked process reciprocity
- `ce` convivial economics ([not in use](http://lov.okfn.org/dataset/lov/vocabs?&page=4) - remember when we would go fishing for two-letter domains? now it's whole namespaces we're appropriating) - could be open enough for future development
- `eso` eco-social organization
- `ess` or `esslocal` (local) eco-social subsistence

else in this order
- `rea+`
- `rea2`
- `rea` 
- `ovn` (for historical reasons, obviously)

---

À propos `exchange` in https://github.com/openvocab, please also have a look at slide No 5 from http://keimform.de/2015/presentation-from-commons-to-commonism/, **Contribution** vs. **Exchange**. That's too much polarizing and not on the same granularity level as here, right?

---

`rea2000`

**Comment by fosterlynn** [comment]
@almereyda  for sure, jump on in, very glad you're here!

> Contribution vs. Exchange. That's too much polarizing and not on the same granularity level as here, right?

Yeah, I can maybe sort of get where they are coming from.

Exchange here just means things change hands without being changed themselves vs Process they get created, used, etc.  Like I give you half my cookies and you give me a glass of your milk.  That's an Exchange.

**Comment by ahdinosaur** [comment]
@almereyda happy for you to join us. :smile_cat: really keen to bring more awesome minds together.

**Comment by ahdinosaur** [comment]
i think there's three ideas i want to capture in our name, based on [what i consider to be our scope](https://github.com/openvocab/agent/issues/22#issuecomment-142491025):
- fractal networks of social agents (i.e. [holons](https://blog.dinosaur.is/life-as-a-holon/))
- define, plan, account for economic systems (i.e. [rea](https://github.com/valnet/valuenetwork/wiki/Concepts))
- streams of activity events (i.e. [kappa architecture](http://www.confluent.io/blog/turning-the-database-inside-out-with-apache-samza/))

so i'd like to temperature check for either `nes` "network economy streams" or `ses` "social economy streams". neither is a fine response.

**Comment by bhaugen** [comment]
@ahdinosaur - this is just me being picky, and nobody understands the distinctions I am making anyway, but still: we differentiate value flows (or resource flows) from value streams, and I don't necessarily think of value streams as kappa architecture. (Although I could always be missing something, so you could enlighten me.)

Value streams are like the Activity Stream model that @elf-pavlik and @fosterlynn have mentioned several times in their LOD discussions. They are pub-sub streams published by one agent and optionally subscribed to by other agents, and many of the posts in the stream will be actionable (that is, like offers and wants, may kick off conversations for action).

Resource (or value) flows are more essential, I think. They are the stuff of value that flows through processes and exchanges from one agent to another to another to another, potentially circling the Web. They are what ties economic networks together. For another example, IPO Tables are also interested in these flows, and I do consider them to be a potential application of the vocab, although I don't know what they are doing these days.

Anyway, if it comes to words in a name, I'd rather see flows than streams, but don't necessarily need either.

Kappa architecture is interesting, and may in fact be the best way to develop apps these days, but I don't see where it is essential to the vocab. I think the vocab should be usable from command lines and email and chat.

**Comment by fosterlynn** [comment]
How about:

value flows (vf), kind of riffs on activity streams, simple

**Comment by ahdinosaur** [comment]
@bhaugen :+1: everything in your comment, thanks.

@fosterlynn: keen on `vf` value flows, also [not taken(?)](http://lov.okfn.org/dataset/lov/vocabs?q=vf).

**Comment by fosterlynn** [comment]
Anyone not like vf value flows?  If everyone is OK, let's do it!

**Comment by fosterlynn** [comment]
https://www.isnic.is/en/whois/mini?query=valueflows

**Comment by almereyda** [comment]
vf:agree

_Note to self:_ GitHub doesn't allow MarkDown in E-Mail replies, despite it states so in the interface above while editing a comment.

**Comment by ahdinosaur** [comment]
began the rename to `valueflows`. :tada:

**Comment by fosterlynn** [comment]
@ahdinosaur awesome!  Closing the issue.

**Comment by elf-pavlik** [comment]
@almereyda @ahdinosaur ...  **valueflo.ws** available :wink: 
gandi.net allows at least 3 accounts set to access domain configuration
I also like https://iwantmyname.com/about (met founder from NZ islands in Berlin) but not sure if multiple accounts can access domain config...

**Comment by fosterlynn** [comment]
@elf-pavlik does that mean you think we should get our own domain name?  (Sometimes I can't tell what you actually think! :wink: )

I'm fine with that if people think that is best - and can contribute some $ towards registering it for some time.  

Bob and I have an account at Site5, so could host it for no additional money.  Would need to check on how many can access.  I'm sure others have server options too.  (I don't have any knowledge of what company would be better or worse.)

Re-opening the issues since there is more discussion here...

**Comment by ahdinosaur** [comment]
@elf-pavlik keen to jump on **valueflo.ws**. [i asked our question to a friend who works at iwantmyname](https://twitter.com/ahdinosaur/status/648967867866611712), they seem pretty cool, i typically work very close to their office in Wellington, New Zealand. once we have a domain, i reckon we should stick with GitHub pages so we don't have to worry about hosting or uptime or being globally available, plus then deploy access is linked to push access to our repos here, even if they aren't open source.

**Comment by nupfel** [comment]
@elf-pavlik @ahdinosaur technically we can do that at iwantmyname, but all 3 accounts would have full access, not just to the DNS part, which can make ownership and unwanted changes during conflicts a legal issue, I guess. I'd recommend to create a separate account and share creds, if that's an option for you.

**Comment by ahdinosaur** [comment]
thanks @nupfel. :) @elf-pavlik how do you feel about creating a separate account and sharing creds? otherwise i'm also happy with gandi.net.

**Comment by elf-pavlik** [comment]
thanks @nupfel :bow: @ahdinosaur @fosterlynn full access to domain sounds like what we need! can two of you create accounts (and maybe also @almereyda) and assign them to **valueflo.ws** ? I must admin having more sympathy to iwantmyname.com than gandi.net, especially that you have friend relationship :smile: 

@fosterlynn w3id.org provides just redirect service and we need to redirect it somewhere, also documentation of all the vocabs needs e-home. At the same time I see no big problem with starting from gh pages and moving to independent domain sometimes later.

**Comment by fosterlynn** [comment]
@elf-pavlik Yes, understand w3id is just redirect. So that means that our official url will be under w3id, correct?  So, if we do that, no need to do valueflo.ws or use some server other than gh for now?

Alternatively, if we do valueflo.ws, we don't need w3id, correct?

**Comment by fosterlynn** [comment]
How much does iwantmyname.com cost for hosting?  That is what this is about, right, not just getting the domain name?  Just trying to catch up, sorry....

**Comment by elf-pavlik** [comment]
> Yes, understand w3id is just redirect. So that means that our official url will be under w3id, correct?

URLs used in data for vocab terms will use https://w3id.org/valueflows/ prefix  (for stability and longevity) but we still need to publish documentation somewhere. For now https://valueflows.github.io/ should do, but it does not allow content negotiation which at some point would come handy. As I said, we don't need to rush with it and maybe better to have a call sometimes soon and also decide on that while we can talk in real time

**Comment by ahdinosaur** [comment]
> How much does iwantmyname.com cost for hosting? That is what this is about, right, not just getting the domain name?

nah, we only need the domain name since we'll use GitHub pages for hosting or i have a silly heap of Digital Ocean credit if we would rather have our own server.

> Alternatively, if we do valueflo.ws, we don't need w3id, correct?

even with valueflo.ws, we should still use w3id as our primary URL (especially for vocab terms), but it doesn't hurt to have a legitimate domain behind the w3id redirect instead of just valueflows.github.io.

so, who wants to initiate the domain registration (i imagine only this person will show up in the WHOIS)? should i? if so, how long do we want our term to be for? @elf-pavlik you mentioned 5 years, you still think we should do that?

**Comment by elf-pavlik** [comment]
@ahdinosaur SGTM if you would like to register the domain name and use your contact info in WHOIS. Since we will use w3id.org I see no problem with starting with just one year registration and extending it later.

**Comment by fosterlynn** [comment]
@ahdinosaur @elf-pavlik Got it, all seems fine to me.

**Comment by ahdinosaur** [comment]
done, i'll figure out how we can share access sometime soon.
