### ISSUE TITLE
URL for the vocabulary

### ISSUE THREAD

**Issue by fosterlynn** [valueflows/agent#23]
We'll need to host the vocab somewhere.  Like the context and the documentation.

Isn't there some service for hosting random vocabularies?  Or should we pony up for a domain name and use someone's server?  Or are we connected enough to w3c?

The URL will need to be kind of permanent.

**Comment by ahdinosaur** [comment]
i'll host a server, we cool with `openvocab.is`?

**Comment by fosterlynn** [comment]
Let's think about the name - see issue #22 

But also - awesome @ahdinosaur !

**Comment by ahdinosaur** [comment]
as mentioned in https://github.com/openvocab/definition/issues/2, it's probably easiest if we host it on GitHub pages, so that way it is automatically linked in with our GitHub org and repos.

**Comment by elf-pavlik** [comment]
I recommend https://w3id.org/ which in turn can redirect to _openvocab.is_
- https://github.com/perma-id/w3id.org/issues/81
- https://www.isnic.is/en/whois/mini?type=all&query=openvocab

@ahdinosaur If we prefer to use independent domain for namespace, I would propose requirement of registering it for min 5 years and at least 3 people having admin access to manage it!

**Comment by almereyda** [comment]
Any reason why [purl.org](https://purl.org/docs/index.html) would be out of the game?

It has some use http://lov.okfn.org/dataset/lov/vocabs/essglobal

But can be any domain, and especially in terms of autonomy, a GitHub distangled hosting can also have its upsides.

**Comment by fosterlynn** [comment]
@almereyda Yes, I've seen it while poking around for vocabs.  Do you think it will be around for a while?   Do you know who runs it, pays for it, etc.?  (So I don't have to do my own research...  :smile: )

**Comment by elf-pavlik** [comment]
this article also tries to answer question "Why not purl.org"
http://manu.sporny.org/2013/perma-id/

**Comment by fosterlynn** [comment]
So, here is a proposal, based on what has been discussed and linked.

First, about the URL that everybody would see and use into the future:
- I'm hesitant to use github because it is not open source, seems like the wrong way to go long term.
- I don't have a need for our own domain name if we can count on something else that is basically supporting the commons to remain alive.  And really, it might be more risky for our little vocab to have its own place, since we are few and just starting.
- I'm good with [w3id.org](https://w3id.org/) based on elf's recommendation and link, vs purl.org. 

So using w3id.org would also require that we put it somewhere, as it is basically a redirection service.  Github pages would seem fine for that for now, if that is the easiest.

What do you all think?

**Comment by ahdinosaur** [comment]
@fosterlynn :+1: for the proposal.

**Comment by ahdinosaur** [comment]
forked [w3id.org](https://github.com/perma-id/w3id.org) and [added `valueflows`](https://github.com/perma-id/w3id.org/compare/master...valueflows:master). @elf-pavlik can i haz a review before i squash and pull request? i'm also open to waiting until we have more to show in case this invites attention.

**Comment by elf-pavlik** [comment]
@ahdinosaur LGTM please squash & make PR :+1:

**Comment by ahdinosaur** [comment]
[success](https://github.com/perma-id/w3id.org/pull/137#event-426424264)! our URL is now http://w3id.org/valueflows/. :)

**Comment by elf-pavlik** [comment]
> success! our URL is now http://w3id.org/valueflows/. :)

Let's all please use HTTPS https://w3id.org/valueflows/

http://www.w3.org/2001/tag/doc/web-https

**Comment by almereyda** [comment]
Can I assist in setting up TLS for https://valueflo.ws, which doesn't work
yet?
It seems we should make it available right from the start, so no http links
get spawned over the web.

**Comment by fosterlynn** [comment]
@almereyda  sounds like a good idea.  Does the certificate cost much?

**Comment by elf-pavlik** [comment]
let's make a new issue for that in https://github.com/valueflows/valueflo.ws ?

**Comment by ahdinosaur** [comment]
@fosterlynn made an issue [here](https://github.com/valueflows/valueflo.ws/issues/6).
