### ISSUE TITLE
split Relationship and RelationshipType into separate repo

### ISSUE THREAD

**Issue by ahdinosaur** [valueflows/agent#27]
i'm enjoying having a repo per vocab (e.g. `resource`, `process`, `exchange`), i propose we split `relationship` away from `agent`.

how do we feel about this?

**Comment by fosterlynn** [comment]
@ahdinosaur Clearly we have different intuitions about this. :smile:   (All the better for good discussions!)

I'm not sure how to define the way I think about it, but to me there are logical groupings where things are coupled more tightly than other places, and there is some kind of optimal size too.  When I think of Agent, I definitely include the relationships.  If we do personas, I would include that too; and probably the credential side even.  Or maybe not that, I don't know.  But it is stuff that a person needs to think about together in some way.

So I would put Resources and Resource Types together.

Exchanges and Processes seem good to separate, although both will include events.  I could think about Event and Event Type as a separate repo, since you can have events without a process and without an exchange.

There are still lots of edge things, like agent resource relationships for example.

But a question: what do you like about smaller and more repos?  Since this won't affect the final vocab, it is more about how we as a team want to think about it and manage it.....

**Comment by ahdinosaur** [comment]
> what do you like about smaller and more repos? Since this won't affect the final vocab, it is more about how we as a team want to think about it and manage it.....

i like [small modules that do one thing and do it well](https://github.com/mattdesl/module-best-practices#module-basics). lately i've been working with [folks at Enspiral Dev Academy](http://devacademy.co.nz/) about what we're doing here, sharing [my vision of making apps easier to design, build, and maintain by providing common abstractions you can easy install and plug together](https://github.com/openappjs/core). the way i see this happening is by each "module" being a small single-purpose chunk of vocabulary (each instance and respective type definition), which can easily be used to [automatically generate database models, an api interface, a cli interface, an html interface, etc](https://github.com/valueflows/agent/issues/6). this is at least where i'm heading in the long-term, a lot of small steps still to go. :cat:

**Comment by bhaugen** [comment]
@ahdinosaur - I like your vision, and liked it the first time I saw it. I think it follows Conway's Law in being the fitting system architecture for the evolving human organization. The questions remain of the fitting size, scope, boundaries, for each module, and more importantly (I think) how they fit and work together.

See also [visual explorer pipe dream](https://docs.google.com/presentation/d/1N81Q0uDjA7OMEZTLNig6O-MLuWHgb5TL0IxPZ2U8qDU/edit#slide=id.gb7a109124_0_0). Continue to the slide about traversals.

What's happening with this vision at Enspiral? The last signals we saw were skeptical at best.

**Comment by ahdinosaur** [comment]
>  The questions remain of the fitting size, scope, boundaries, for each module, and more importantly (I think) how they fit and work together.

agreed, and i don't have an answer other than to do more learning experiments. :smiley: 

> See also visual explorer pipe dream

makes me happy every time i see it, keen to merge the visions somehow. :fireworks: 

> What's happening with this vision at Enspiral? The last signals we saw were skeptical at best.

eh, Enspiral's an amorphous gooey network of autonomous agents all with their own visions. there's some that share our vision and some that are skeptical, i've learned to collaborate with the former and not bother with the latter. there's a lot of energy for collaboration, most folks just need a straightforward path to start contributing that a) isn't confusing, and b) helps them achieve their own goals. it's a long marathon with a lot of small steps towards this end, i'm happy with the journey.

i think it'd be good to figure out what the smallest achievable deliverable towards the visual explorer vision would be, probably best in another issue in the home repo. otherwise i'm using Holodex as a excuse to build tooling that gives the vocabs some arms and legs you could say.

---

back on this topic, i think the most compelling case for splitting out relationship is what @fosterlynn mentions about agent resource relationships. splitting out relationship would help us clarify that it's not only between agents, it also should be possible between agents and resources. unless we want them coupled, but i think for the sake of minimalism we want as much de-coupled to be re-used in other parts of the overall vocab, maybe?

**Comment by bhaugen** [comment]
@ahdinosaur @elf-pavlik - re visual explorer.

When we get some real LOD published that could be linked (and I get a bit more educated on how it is supposed to work), I want to find some existing tools that will let me walk the links. Doesn't need to be visual to begin with, just needs to support walking. That will help me a lot in figuring out what is a module, what are its arms and legs, and what do they have in their hands and prehensile feet.

![Shakti](http://www.indianetzone.com/photos_gallery/3/amba_19074.jpg)

**Comment by elf-pavlik** [comment]
I would suggest not creating to many repositories to early! We will need to also look at various types of relationships 
- Agent <-> Agent
- Agent <-> Process
- Agent <-> Exchange
- Agent <-> Resource
- Process <-> Resource
- Exchange <-> Resource

etc.

BTW I just added placeholder for https://w3id.org/role where I plan to experiment with
- attendee
- organizer
- speaker
- host
- guest
- member
- chair
- staff

Some examples in https://github.com/hackers4peace/plp-test-data/blob/master/w3c-social.jsonld

**Comment by bhaugen** [comment]
I agree about not creating too many repositories too early. Do you think any of those that have been separated out so far were created too early? (So far, I don't. But then, I have not tackled a README for the resource repo yet...)

> Agent <-> Process
> Agent <-> Exchange
> Agent <-> Resource
> Process <-> Resource
> Exchange <-> Resource

Each of those relationships has particularities, and few of them are simple: 
- In many cases, the relationship is mediated by something else. In other words, it is not a direct relationship between (for example) an Agent and a Process, but maybe an Agent <-> a Commitment or an Event <-> and a Process.
- In many cases, multiples of one of the things will have a mediated relationship with the other thing. For example, many Resources may be transferred between different Agents in an Exchange.
- Or two of the things in one of those lines may have many different types of relationships with each other. For example, an Agent may own a Resource, or create a Resource in an Economic Event, or destroy a Resource in an Economic Event, or offer to provide a Resource on request, or any of several other possible ways that Agents and Resources could be related.

I'm not necessarily disagreeing here, but those thoughts come to mind immediately. And need to be detailed out. We've been detailing out the Agent <-> Agent relationships so far.

**Comment by elf-pavlik** [comment]
Some examples of relationships (direct/unqualified) from schema.org
- http://schema.org/provider
- http://schema.org/seller
- http://schema.org/buyer
- http://schema.org/producer

To get qualified version we could use patter I describe in https://github.com/w3c-social/social-vocab/wiki/Verbs---owl:Class-vs.-rdf:Property#qualified-relations

IMO we should also take a closer look at http://www.gs1.org/gtin-plus eg. search for 'OrganizationRole' in http://www.gs1.org/sites/default/files/docs/gtin_plus/gs1Voc_v1.ttl

**Comment by fosterlynn** [comment]
> back on this topic, i think the most compelling case for splitting out relationship is what @fosterlynn mentions about agent resource relationships. splitting out relationship would help us clarify that it's not only between agents,

Actually, I don't think that the same Relationship we use for agent to agent relationships will be used for relationships between agents and resources.  I understood the definition in AS to be between agents.  Although they use the term "individual", which may be broader than I think, who knows.

Even besides that, I think defining Relationship so you can use it as a relationship between anything and anything else is over-generalization - can be done but is not helpful.  But I could be wrong, might be a bit different in LOD.

But in any case, even if we do use Relationship to mean lots of different kinds of relationships, I still think we should take them one at a time within the vocab we are thinking about, so we can finish each area (repo).  If we re-use things from something we already finished, all well and good, it's already in the context.

**Comment by ahdinosaur** [comment]
great feedback by all, i'm gonna close this issue for now, we can always revisit it later if we feel we should.
