### ISSUE TITLE
add few more examples of agents to start working on relationships

### ISSUE THREAD

**Issue by elf-pavlik** [valueflows/agent#29]
So far we have one Person and one Group, I will add soon another Person and Group which will have names in multiple languages to work on supporting it from very beginning. Besides that we need few more examples to start working on ... **relationships**
### People
- [x] @elf-pavlik
- [x] @fosterlynn 
- [x] @bhaugen 
- [x] @ahdinosaur 
### Groups
- [x] @hackers4peace
- [ ] OuiShare
  - [ ] OuiShare Labs
- [ ] @enspiral
  - [x] @craftworks
  - [ ] @loomio
- [x] @mikorizal
- [x] @sensorica

No need for PR for editing one's own data, if we touch JSON-LD context let's go through PR flow

**Comment by almereyda** [comment]
We have moved the ValueFlows organization from GitHub to https://lab.allmende.io/valueflows.

This issue has been closed here, and all further discussion on this issue can be done at

> https://lab.allmende.io/valueflows/agent/-/issues/29.

If you have not done so, you are very welcome to register at https://lab.allmende.io and join the ValueFlows organization there.
