### ISSUE TITLE
Use case for w3c

### ISSUE THREAD

**Issue by fosterlynn** [valueflows/agent#3]
@elf-pavlik has persuaded me to participate with him in the social interest group in w3c - so that the work on vocab can have broader reach.  I'm thinking to submit a use case that will address the question of flexibly defined relationships.  Enspiral's holodex provides a nice clean but interesting one I think.  @ahdinosaur and @simontegg please offer additions and corrections as needed.  (I wasn't sure how the steward relationship works; and if it has any differences that would affect the model relative to mentor.)

Proposed use case:
1. An organization has a number of members who are considered as peers within the organization.
2. Each member has another member assigned as their mentor.
3. One person is always assigned the position of desk collector, which has specific responsibilities (collecting money each month for use of a desk in the shared space).  This responsibility rotates occasionally.

**Comment by ahdinosaur** [comment]
@fosterlynn awesome! good on you for being our ambassador to the w3c, i reckon i'm a bit too jaded about traditional standards bodies to be able to do it myself, but i really appreciate support in this regard and value the importance of extending our reach by connecting with more mainstream venues for collaboration.

submitting use cases for the systems we want to make possible is a great idea. the use case you outlined so far is great, i'll try and think some more if i can offer any possible improvements or additions.

**Comment by elf-pavlik** [comment]
@fosterlynn this use case sounds little static to me and doesn't seem to explain requirements for expected online **interaction**. What do you think about formulating it/them more in direction of [Social API User Stories](https://www.w3.org/wiki/Socialwg/Social_API/User_stories)?

**Comment by fosterlynn** [comment]
@elf-pavlik thanks very much, I see your point and hadn't noticed that in the existing use cases.  I have re-worked below and added a bit from Sensorica for this second draft to try to make it more social.  Re-reading, I'm not sure I have totally succeeded, probably because in my mind this is a data vocab/ontology requirement and I don't care how the interaction happens, but hopefully it is better.  I'm happy to work on it more.  :smile:  Again, I appreciate feedback, thanks y'all! 
1. Several people decide to form a loose (non-legal, peer-to-peer) organization to work together on projects, share a space, and want to openly invite people online to join them.
2. They set up the organization with a name and website, record themselves as _members_ of the organization, and issue an open invitation to other people to join them as _members_.
3. They then decide that _member_ is too strong a term for what they want to convey to others who might want to join, and change their relationships with the organization to _affiliate_.
4. They also want one affiliate to take responsibility to collect money from everyone to pay the rent for the space, so they post a position called _desk collector_ for the organization.  Someone volunteers and assigns themselves to the position. 
5. After a few months, that person is tired of collecting money, and removes themselves from that position.  The position remains empty for a week, and then someone else volunteers to collect money for a while, and assigns themselves to that position.

**Comment by elf-pavlik** [comment]
Sounds better, now we have _form_, _invite_, _join_, _change_, _collect_, _pay_, _post_, _assign_, _quit_. Looks like some social interaction happening online and offline :smile:

**Comment by fosterlynn** [comment]
@elf-pavlik  ok good, thanks again.

@ahdinosaur  said: "good on you for being our ambassador to the w3c, i reckon i'm a bit too jaded about traditional standards bodies to be able to do it myself."  Mikey, believe me, I can completely relate to that statement and I am filled with dread!  But I will give it a good try and see if we can get something done fairly quickly....  :smile:
