### ISSUE TITLE
audibleName & audibleNameMap - which makes possible to hear pronunciation of a name

### ISSUE THREAD

**Issue by elf-pavlik** [valueflows/agent#31]
I would like to add property which links to an audio file, this way one can hear pronunciation of a name

e.g. https://en.wiktionary.org/wiki/listen#Pronunciation

(I just can't remember how to pronounce mikorizal :wink:  )

I could make example and PR right after we decide on merging (or not) of #30

**Comment by ahdinosaur** [comment]
this is a great idea. is there any prior work in the semantic web ecosystem for something like this? it seems like a general accessibility feature very similar to internationalization, seems silly that we'd have to make a property to support audio for another property. if this isn't a solved problem then audio for names is a good place to start before trying to do audio for all the things.

**Comment by elf-pavlik** [comment]
> silly that we'd have to make a property to support audio for another property. that being said, if this isn't a solved problem then audio for names is a good place to start before trying to do audio for all the things.

I agree, but since we still **prototype** here we can include this feature and than make sure to migrate it to more general pattern in case where we find|create one.

**Comment by ahdinosaur** [comment]
@elf-pavlik that feels good to me, in general i'm happy to go with what works for now _as long as we make an issue to track our more ideal long-term plan_.

**Comment by almereyda** [comment]
We have moved the ValueFlows organization from GitHub to https://lab.allmende.io/valueflows.

This issue has been closed here, and all further discussion on this issue can be done at

> https://lab.allmende.io/valueflows/agent/-/issues/31.

If you have not done so, you are very welcome to register at https://lab.allmende.io and join the ValueFlows organization there.
