### ISSUE TITLE
Direction of relationship in spo format

### ISSUE THREAD

**Issue by fosterlynn** [valueflows/agent#45]
I think this can be discussed as a specific issue, although it is related to https://github.com/valueflows/agent/pull/40#issuecomment-147233712, and #52 in valueflows repo, and probably others.  (If it seems too related, let's pull it somewhere else.)

My question is: In the following example, how do we actually tell which way the relationship goes?  In the discussion, @elf-pavlik and @ahdinosaur assumed different directions to "member", and many people will do so.  You can sort of figure it out in this case, but you never could if it is "mentor" for example.  Do we need to think about this differently?  Name things differently? Something else?

``` jsonld
{
  "@context": [
    "https://rawgit.com/valueflows/agent/master/context.jsonld",
    {
      "dex": "https://holodex.enspiral.com/api/"
    }
  ],
  "subject": "dex:people/mikey",
  "relationship": "member",
  "object": "dex:groups/enspiral-craftworks"
}
```

**Comment by elf-pavlik** [comment]
1) Each definition of property can include diagram with an arrow
2) formal rdfs:domain (type of subject) & rdfs:range (type of object) - causes inferences

``` json
  {
        "@id": "member",
        "@type": "owl:ObjectProperty",
        "rdfs:domain": "foaf:Group",
        "rdfs:range": "foaf:Person",
        "rdfs:label": {
            "en": "member"
        },
        "owl:inverseOf": {
            "rdfs:label": {
                "en": "member of"
            }
        }
    }

```

3) less formal schema:domainInludes & schema:rangeIncludes - no inferences but just a hint

**Comment by fosterlynn** [comment]
Closing this, Not an issue if the relationship directions are separated.
