### ISSUE TITLE
vf:property instead of vf:relationship

### ISSUE THREAD

**Issue by ahdinosaur** [valueflows/agent#46]
from https://github.com/valueflows/agent/pull/37#issuecomment-146963657,

> @elf-pavlik: How about s/relationshipType/relationshipProperty/ or even simply using for now vf:property seeing when we really need
> vf:relationshipProperty rdfs:subPropertyOf vf:property ?

this is an interesting idea, so here's a dedicated issue for discussion.

**Comment by elf-pavlik** [comment]
@ahdinosaur since this Relation(ship) design pattern seems not specific to Agent, can we take it to https://github.com/valueflows/valueflows/issues/63 ?

**Comment by ahdinosaur** [comment]
@elf-pavlik yes :+1:
