### ISSUE TITLE
Can we use "name" for agents?

### ISSUE THREAD

**Issue by fosterlynn** [valueflows/agent#53]
We agreed to use skos:prefLabel for the label or name for everything.  We now have in our context:

```
"label": "skos:prefLabel"
```

Can we in similar vein have 

```
"name": "skos:prefLabel"
```

and use that for agents?

Would that make it hard on the display end?  If so, can we make them equivalent in some way?

I know there continues to be a tension between naming for graphing and naming for domain understanding.....  I would like to push it towards domain understanding as much as we can, understanding we will need some consistency for ease of coding.  What do you all think?

**Comment by ahdinosaur** [comment]
relevant: https://github.com/valueflows/agent/pull/49#issuecomment-149851072, basically if you alias two properties to the same linked data property, JSON-LD expansion and compaction will normalize both into one of the aliases.

> I know there continues to be a tension between naming for graphing and naming for domain understanding. I would like to push it towards domain understanding as much as we can, understanding we will need some consistency for ease of coding.

yay i agree. this was my motivation for https://github.com/valueflows/agent/pull/49, although there were issues with my particular proposal there.

**Comment by ahdinosaur** [comment]
another option is we remove 

```
"label": "skos:prefLabel"
```

in favor of

```
"name": "skos:prefLabel"
```

**Comment by fosterlynn** [comment]
@ahdinosaur  Thinking I might like it, but don't have in mind everything we might need labels for.  And let's see what @elf-pavlik says.

**Comment by elf-pavlik** [comment]
@fosterlynn if you would like to rename 'label' and 'labelMap' to 'name' and 'nameMap' I see no problem, actually even like it by lowering chance for cognitive mixing it with label as 'tag'. I initially used 'displayName' and 'displayNameMap' before https://github.com/valueflows/valueflows/pull/70

If you see need for for two different DataProperty instances 'name' and 'label' than you and @ahdinosaur may want to discuss it in https://github.com/valueflows/valueflows/issues/34

Most likely in named issue we can also entertain renaming 'note' and 'noteMap' to 'description' and 'descriptionMap'

**Comment by fosterlynn** [comment]
Moving the discussion to previous issues: https://github.com/valueflows/valueflows/issues/34
