### ISSUE TITLE
vf:controls

### ISSUE THREAD

**Issue by elf-pavlik** [valueflows/agent#54]
I have impression that in our discussions about agents, their group dynamics and slowly getting into concept of 'ownership' of resources. We may miss explicit presence of IMO key aspect to that conversation **control**.

What I see makes agents distinct, they can **act** (have agency), and to act they need to **make decisions**. We could look at relationship of Person (individual) to a Group (collective) in terms of "what degree of **control** given individual has, when it comes to decisions on how the group **acts**" (encapsulating inner group dynamics to interface with other entities as single agent)

Similar when it comes to owning a resource, especially when Group (collective involving many individuals) owns a resource. It controls this resource and again deciding about it has some inner group dynamics, again encapsulate to appear as single agent when interfacing with the rest of economic environment.

I think property like _vf:controls_ makes sense in Agent -> Agent relations (a person has certain degree of control in group decisions) as well as Agent -> Resource relations (a person has certain degree of control in decisions about particular resource)

Just putting it here for discussions, seeing it relevant to
- https://github.com/valueflows/agent/issues/38#issuecomment-150235976
- https://github.com/valueflows/agent/issues/51#issuecomment-150373794
- https://github.com/valueflows/agent/issues/20#issuecomment-150228915

As well as some project of various friends
- http://influencemapping.org/
- https://data.openoil.net/
- http://alpha.whocontrolsit.com/

**Comment by bhaugen** [comment]
@elf-pavlik - when I read your commentary above, two thoughts came to mind:
- In previous networks, we've seen the Agent:Resource relationships Owner, Planner (does not own but makes decisions about), Custodian (does not own but has physical custody and responsibility), Manager, Technician (certified to use), Trainer, Certifier, and probably some others I can't think of right now.
- Re Agent:Group relationships, we know several people in several networks who are concerned about governance, and would like system support in that arena: for example, in making and recording group decisions. I think that is where Loomio originated, for example. Kurt Laitner has studied this issue a lot.

**Comment by elf-pavlik** [comment]
> Planner (does not own but makes decisions about)
> As I understand, someone having _sth:planner_ relationship with resource can NOT decide to pass _sth:ownership_ relationship to someone else?

Maybe we can map roles to verbs, in terms of which role can perform which set of verbs on given resource. Eg. 
- _role:planer_ can NOT _verb:transfer_ but can _verb:lend_ etc.
- _role:driver_ can _verb:drive_, _verb:repair_, _verb:lock_, _verb:unlock_ etc.

Reminds me of this RoR plugin https://github.com/ryanb/cancan/wiki/Defining-Abilities
and https://www.w3.org/wiki/WebAccessControl#Modes_of_Access

**Comment by bhaugen** [comment]
Sensorica calls that Access Rules. For example:

> Co-owners have unlimited access. 
> FabLab members have access through the Managers. 
> TechShop clients have access through the Managers. 
> See more here
> https://docs.google.com/document/d/1U5NTRUHna6vYnv6riKyUrl8Xn8kn2K7ShrzaBy_ZyUM/edit

From http://nrp.sensorica.co/accounting/resource/411/

**Comment by fosterlynn** [comment]
> Maybe we can map roles to verbs, in terms of which role can perform which set of verbs on given resource.

@elf-pavlik  I like RDF thinking influencing app thinking for a change for me!  :smile:  I say this because we have implemented only the minimum needed for resource access rules in NRP.  We may need to implement rules that can be used by the computer instead of the human reader of text, but we have hoped that someone else would write a separate app for that, that could be used for managing sharing resources across networks.  This was in the works for a while at Sensorica, when they were trying to organize a large shared space, but that fell apart.  But it would require some vocabulary for sure!

**Comment by almereyda** [comment]
We have moved the ValueFlows organization from GitHub to https://lab.allmende.io/valueflows.

This issue has been closed here, and all further discussion on this issue can be done at

> https://lab.allmende.io/valueflows/agent/-/issues/54.

If you have not done so, you are very welcome to register at https://lab.allmende.io and join the ValueFlows organization there.
