### ISSUE TITLE
Organization/LegalAccount sioc:UserAccount (foaf:OnlineAccount)

### ISSUE THREAD

**Issue by elf-pavlik** [valueflows/agent#55]
I just had another look at [sioc:UserAccount](http://rdfs.org/sioc/spec/#term_UserAccount) as explained in http://sioc-project.org/node/341

![sioc:UserAccount](http://sioc-project.org/files/sioc_foaf_skos_useraccount_change.png)

It has certain 'agency' limited to web/online resources, and have associated foaf:Agent (usually foaf:Person). In a similar way we could model Organizations - they would have 'agency' **limited** to legal activities and always have associated a real Agent (Person or Group).

**Comment by fosterlynn** [comment]
> In a similar way we could model Organizations - they would have 'agency' limited to legal activities and always have associated a real Agent (Person or Group)

@elf-pavlik I would like to understand why you are so shy of Organization.  I get that the world has a lot of organizations that are in the belly of the beast, perhaps most.  But here are the use cases I know about and personally support:
- Networks buy from organizations and sell to organizations, sometimes buy from Walmart or Exxon-Mobil.  They need to record these exchanges.  They don't care to record the people behind these organizations, not needed.
- Some people want a more formally structured organization for themselves, like people who organize cooperatives.  I belong to more than one cooperative that I consider part of the moving to the next economy. 
- A vision of a few people we have worked with, and of us in our region, is of regional economic ecosystems.  This could include networking existing local small businesses.

This is a transitional period, and this vocabulary will need to support many transitional efforts.  And groups are experimenting, so there will be lots of things going on, some of them possibly wacky.  But who is to say what is wacky?  

My opinion: 
- We don't want to get in the business of fine tuning what "we" think people need in the way of organization, either for themselves or who they choose to trade with.  We want to be radically inclusive at this stage, not pure.
- Organization the term is prevalent in existing vocabs, and it mostly exists on the same level as Group.  Which I think is correct, neither inherits from the other.  And there is no reason to make people define Organization in their own vocabulary.
- Organizations in this model need as much agency as people or groups.  And in any case, it helps to keep it simple.

Not intended to be a rant, hope it doesn't come off as one!  Disagreement welcome, my friends!  :smile:

**Comment by elf-pavlik** [comment]
@fosterlynn so far Agent with Person (individual) and Group (collective of individuals and possibly sub groups) looks like something we may need to distinguish when we implement various software. Unless we can clearly define how Organization puts some restrictions on Agent, which may affect implementations I really don't see reason not to just use Agent and recommend people to add various additional classes to categorize it further.
- `"@type": [ "vf:Agent", "org:Organization" ]`
- `"@type": [ "vf:Agent", "foo:NGO" ]`
- `"@type": [ "vf:Agent", "bar:BCorporation" ]`

I see various benefits in getting used to picking various specialized classes for categorizing entities instead creating lots of hybrid classes just to avoid using many of them on on single entity.

One of possible restrictions that would make it clearly distinguishable from generic vf:Agent that I could think of: has agency only in legal dimension - since it doesn't have physical presence and only exists as legal (conceptual) entity. This way software can know that for interactions happening in physical reality, entity categorized as Organization simply stay out of the game and only agents which have physical presence can do it.

BTW so far only hackers4peace example uses _schema:Organization_. I propose using PR workflow where we provide an example which already uses new term and there discuss why we actually need this new term.

**Comment by fosterlynn** [comment]
@elf-pavlik so you are thinking maybe just stick to Agent and not do any of our own subclassing?  That is an interesting thought.  Puts some more work on people using our vocabulary, but maybe that's fine, since it adds lots of flexibility.  So for example the NRP software might decide to just make everything that is an Organization into an org:Organization (and vf:Agent) for the purposes of LOD communication. Other software might do otherwise.  But the valueflows vocab would not suggest to people how to subclass Agent?

Or along the same line of thinking, we could expand to Agent and Person....  (maybe foaf:Agent and foaf:Person, or not) with some definitions of equivalentClasses in the vocab or the doc?  In our software, we find it useful to know Person and not-a-person.  For example, only people can have userAccounts, as in your example above.  And only a not-a-person can be a context agent.

I think I like this train of thought, although there certainly may be problems I haven't thought of.

**Comment by ahdinosaur** [comment]
eep, seems like a rabbit hole. :rabbit: :black_circle: i look forward to real-world usage to back up these theories. :wink: 

from developing Holodex, we need a simple way to distinguish between agents that are one or many (having sub-agents). it makes sense to have a representation of the virtual accounts that link to real people, but i have no idea what the best solution is till i get my hands dirty in real-world usage, maybe i'll have something to report once we start feeding in virtual account data from loomio, slack, etc.

> I see various benefits in getting used to picking various specialized classes for categorizing entities instead creating lots of hybrid classes just to avoid using many of them on on single entity.

:+1:. make intuitive sense.

**Comment by fosterlynn** [comment]
> maybe i'll have something to report once we start feeding in virtual account data from loomio, slack, etc.

@ahdinosaur any idea of when that might be?  I agree that will be very interesting!

**Comment by almereyda** [comment]
We have moved the ValueFlows organization from GitHub to https://lab.allmende.io/valueflows.

This issue has been closed here, and all further discussion on this issue can be done at

> https://lab.allmende.io/valueflows/agent/-/issues/55.

If you have not done so, you are very welcome to register at https://lab.allmende.io and join the ValueFlows organization there.
