### ISSUE TITLE
agent link dumps

### ISSUE THREAD

**Issue by bhaugen** [valueflows/agent#61]
What if anything does this mean to us?
http://android-developers.blogspot.com/2016/02/announcing-people-api.html

Ontologically, what is a contact?

**Comment by bhaugen** [comment]
http://qntm.org/gay
Or, as the article says, 

> **Note: By popular demand, this problem is now known as "Y2gay".**

Hat tip @simontegg  and Sam Parkin in an Enspiral Slack channel.

**Comment by almereyda** [comment]
We have moved the ValueFlows organization from GitHub to https://lab.allmende.io/valueflows.

This issue has been closed here, and all further discussion on this issue can be done at

> https://lab.allmende.io/valueflows/agent/-/issues/61.

If you have not done so, you are very welcome to register at https://lab.allmende.io and join the ValueFlows organization there.
