### ISSUE TITLE
What is, and what is not, an Agent

### ISSUE THREAD

**Issue by bhaugen** [valueflows/agent#63]
In general, Agents are people and organized groups of people, where the group has an identity.

Agent is related to the concept of [Agency](https://en.wikipedia.org/wiki/Agency_%28philosophy%29): Agents make decisions in relationships with other agents and in groups. In Value Flows, we are concerned with agents participating in online social-economic networks: especially economic networks.

As of the date of this posting, nothing else is an Agent in this vocabulary. Robots are not ready yet to make autonomous decisions in social-economic networks. Algorithms may make decisions, but they do so only when they were created by people. Other living creatures are agents in ecosystems, but to participate in online communities, they would need people to be their proxies.

Economic Agents are a subset of people and groups that make decisions and take actions on Economic Resources. Any agent can be an economic agent in some context, but may not be.

**Comment by elf-pavlik** [comment]
I think that only Agent can make commitments and other agreements. I think we should stay careful when we want to define some subset of Agent which members can NOT make commitments and other agreements - responsibility etc.

**Comment by bhaugen** [comment]
Agreed.

**Comment by almereyda** [comment]
We have moved the ValueFlows organization from GitHub to https://lab.allmende.io/valueflows.

This issue has been closed here, and all further discussion on this issue can be done at

> https://lab.allmende.io/valueflows/agent/-/issues/63.

If you have not done so, you are very welcome to register at https://lab.allmende.io and join the ValueFlows organization there.
