### ISSUE TITLE
vf:Organization

### ISSUE THREAD

**Issue by fosterlynn** [valueflows/agent#68]
Low priority.  Should we include Organization, and if so, should we use foaf:Organization?  Also considered org:Organization.  Ref. #66

**Comment by elf-pavlik** [comment]
> - _does organization has 'member' relationships with agents directly or it has some other (one-to-one) relation with a group and that group has members?_
> - _do we define Organization as sub class of Group? again Group can have just one member_

**Comment by fosterlynn** [comment]
I don't think Organization is subclass of Group.  Neither does any other vocab that defines it.  It is a different animal.  I'm good with foaf:Organization, subclass of foaf:Agent.  And also good with waiting, it is not a very important issue for VF I think.

I see the relationship types that an organization would have with other agents to be exactly the same model as we have and use for groups.  There may be a bunch of different types, which is fine.  "Member" is one choice of many choices, and many organizations won't think of "member" as something they want to use.  In what we have observed, nrp:Organization is mostly used for agents external to the context, with roles like customer or supplier, or for legal organizations that groups or networks need to set up for tactical purposes.
