### ISSUE TITLE
multiple sources of truth and cross validation

### ISSUE THREAD

**Issue by elf-pavlik** [valueflows/agent#7]
Following up on: https://github.com/openvocab/exchange/issues/2
How holodex relationships get stored, where each Agent publishes to its autonomous data space? https://github.com/holodex/enspiral-data/blob/master/relationships.csv

In such case, for each relation between two Agents, we will always have at least two web resources which describe this relation, each from one of the agents perspective. Similar to my comment https://github.com/jasnell/w3c-socialwg-activitystreams/issues/180#issuecomment-119541477

In https://github.com/hackers4peace/plp-docs/issues/12#issuecomment-78043877 I see you use **symetric** property to link both.

Once again, http://opencreds.org/ seem to me very promising here...

**Comment by ahdinosaur** [comment]
great design requirement to bring up.

the approach i have in mind for this is to architect the system where each Agent has their own autonomous data space, where related objects are linked together via URLs.

i'd rather the data provenance, signing, verification, encryption, and decryption be a data layer below the app layer, instead of having to handle that here; for this i'm keen to use [ssb](https://github.com/ssbc/ssb-docs).

**Comment by elf-pavlik** [comment]
Do you hang out with @dominictarr there in far south? :smile: 

When it comes to signaures, Linked Data Signatures seem very attractive to me. Since one signs the _meaning_ of he message and not particular serializaion. So for example if you use JSON-LD, all the formating including white spaces etc. doesn't matter, before signing it goes through graph normalization currently worked on as part of W3C hosted http://opencreds.org/ (see videos after scrolling down)

If we settle at least on common data model, than one can do messagin on top of HTTP, XMPP, PSYC etc. I still find it important that no matter how systems exchange messages, the actual payload can stay the same!

**Comment by dominictarr** [comment]
heeey. btw back in NZ. will be down your ways in sept!

**Comment by elf-pavlik** [comment]
@dominictarr @ahdinosaur how in Secure Scuttlebutt you manage such cases? I guess you just sign everything and verify things by checking signatures. Can we take case of membership in a secret group with a group wall (message board), chat room and calendar?

Can you point me to information on how you manage such membership in secret groups and access control levels (eg. member, admin, moderator etc.)? I need to check new features of github organizations and teams but we could see how to replicate exact that in distributed scenario, including secret organizations and secret teams.

Currently I start implementing [Web Access Control](https://www.w3.org/wiki/WebAccessControl) also used in [SoLiD draft](https://github.com/linkeddata/SoLiD), which BTW should get more push thanks to http://crosscloud.org/jobs/

ping @jnny @fractastical

**Comment by dominictarr** [comment]
@elf-pavlik hey yes in ssb every post is signed. it naturally works well with subjective data. for example, my name for you overwrites your name for yourself. But to get that i must explicitly name you.

We do not have groups implemented yet, though we are thinking about how to do it. I'm fairly sure it will work as a data structure on top of the ssb feeds, but we have just had many smaller bridges to cross to get to this one.

**Comment by almereyda** [comment]
We have moved the ValueFlows organization from GitHub to https://lab.allmende.io/valueflows.

This issue has been closed here, and all further discussion on this issue can be done at

> https://lab.allmende.io/valueflows/agent/-/issues/7.

If you have not done so, you are very welcome to register at https://lab.allmende.io and join the ValueFlows organization there.
