### ISSUE TITLE
How can a group agent make commitments?

### ISSUE THREAD

**Issue by bhaugen** [valueflows/agent#70]
# Preface
If we allow group agents, as I think we do, then they need to have agency. For example, make commitments with other groups, like in a federation of groups.

From gitter chat:
elf Pavlik @elf-pavlik 10:57
i think we may better discuss issues around 'context agent' here so we don't use github issues as real time chat :wink:

Bob Haugen @bhaugen 10:57
:wave:
I told Lynn that I was ok with you and she starting out with just individuals and groups, no context agent concept at first
add it if and when we need it
but I predict that the first way somebody will want it will be "company".
That's why we added context agent, to avoid baking in company or anything remotely like it.

elf Pavlik @elf-pavlik 10:59
great! i think we still need to look at Agent <-> Agent relationship which specifies which individual agents can make commitments 'on behalf' of group agent

Bob Haugen @bhaugen 11:00
that's what the Scuttleverse is talking about. We need to get MIkey into the conversation.
I'll see what I can find that is on the Web.

elf Pavlik @elf-pavlik 11:02
cool! i think that we may simply define an Agent <-> Agent relationship which means that referenced agent can make commitments on behalf of referencing agent

Bob Haugen @bhaugen 11:02
Maybe you could start an issue about that topic and I'll float it by the scuttlers
I think they have a more nuanced set of ideas about the topic
but that relationship might be enuf for now

Lynn Foster @fosterlynn 11:03
cool! i think that we may simply define an Agent <-> Agent relationship which means that referenced agent can make commitments on behalf of referencing agent
like some specific code on the relationship?
the scuttlers may have a whole different way of thinking about it, i suppose

Bob Haugen @bhaugen 11:03
not whole different way
and I don't think they are done yet

elf Pavlik @elf-pavlik 11:03
we can even start with 'committer'

Bob Haugen @bhaugen 11:03
they
they are looking at it from the viewpoint of a protocol

Lynn Foster @fosterlynn 11:04
interesting

Bob Haugen @bhaugen 11:04
what is a group identity?

elf Pavlik @elf-pavlik 11:04
so to see who can commit on behalf of the group, we just need to see who group references as 'committer'

Bob Haugen @bhaugen 11:04
what makes up a group?

Lynn Foster @fosterlynn 11:05
they are deep!

Bob Haugen @bhaugen 11:05
if a group posts something, who did it come from?
everything is represented by a cryptographic key
all nodes in the scuttleverse
if that key identifies a group, what does that mean?
if the group identity posts something, what does that mean?

elf Pavlik @elf-pavlik 11:06
i would like to start with not 'posing as group' but 'posting as oneself on behalf of the group' and other individuals can endorse it with signature
or more than individual can 'author' a post and each one signs it with one's own signature

Lynn Foster @fosterlynn 11:07
i would hope that groups have their own formal or informal internal governance and that not everyone needs to sign every post though!

Bob Haugen @bhaugen 11:07
who wants to start an issue that I can ask the scuttlers about?

Lynn Foster @fosterlynn 11:07
committers is a more narrow issue

elf Pavlik @elf-pavlik 11:07
i feel very hesitant about 'group identity posting'

Lynn Foster @fosterlynn 11:08
i know that

elf Pavlik @elf-pavlik 11:08
sounds to me like 'a voice of big brother' :wink:

Lynn Foster @fosterlynn 11:08
why?

elf Pavlik @elf-pavlik 11:09
i like where people stand behind their statements, while they still can claim to make them 'on behalf' of the group

Lynn Foster @fosterlynn 11:09
like it is a problem if you don't know who posted for the group?
or how many people in the group agree?

elf Pavlik @elf-pavlik 11:09
still distinction of 'group made statement' vs. 'one or more individual made statement on behalf of the group' seems important to me

Lynn Foster @fosterlynn 11:10
ok

Bob Haugen @bhaugen 11:10
do you think that groups can make commitments to other groups?

elf Pavlik @elf-pavlik 11:10
individuals can make commitments 'on behalf' of the group

Bob Haugen @bhaugen 11:10
what if that individual leaves the group?
happens all the time

elf Pavlik @elf-pavlik 11:11
since group authorized that individual to make commitments 'on behalf' of it, i think one may expect group to still respect it

Bob Haugen @bhaugen 11:11
if an individual makes a commitment on behalf of a group, can we assume that the group endorsed that commitment?

elf Pavlik @elf-pavlik 11:11
yes, by endorsing that individual with something like 'committer' relationship

Bob Haugen @bhaugen 11:11
I think we crisscrossed

Lynn Foster @fosterlynn 11:12
so there are various roles within a group that have 'permission' to do certain things... post, agree, commit, etc.?

Bob Haugen @bhaugen 11:12
I think the scuttlers are thinking about something like specific group endorsements of specific commitments made on behalf of the group

Lynn Foster @fosterlynn 11:12
on behalf of the group
there will be also many things that anyone in the group can do

Bob Haugen @bhaugen 11:13
not a role, but we as a group have come to agreement on makign thie commitment
this commitmemt

Lynn Foster @fosterlynn 11:13
like sensorica, anyone can make a commitment, a plan, etc.; in Freedon Coop, they want to assign special role of coordinator for planning

Bob Haugen @bhaugen 11:13
however we as a group come to agreement on things

elf Pavlik @elf-pavlik 11:14
 in Freedon Coop, they want to assign special role of coordinator for planning
i think i see 'committer' relationship/role in such way

Lynn Foster @fosterlynn 11:14
(sorry i was thinking that where @elf-pavlik started from was commitments on processes within the group; different role)

Bob Haugen @bhaugen 11:14
I think groups will have different internal dynamics
different governance etc
like how they come to agreement on what to do as a group

elf Pavlik @elf-pavlik 11:15
ok, i have different option

Bob Haugen @bhaugen 11:15
could be an assigned role
would not need to be

elf Pavlik @elf-pavlik 11:15
group specifies 'collection' for their commitments
they have some way to manage ACL

Preface: if we allow group agents (as I think we currently do), then they need to have agency. That is, be able to do things as a group, like make commitments with other groups. Like in a federation of groups.

Lynn Foster @fosterlynn 11:15
collection of commitments?

elf Pavlik @elf-pavlik 11:16
and only commitments referenced from that collection as 'contained' in it one will consider valid

Bob Haugen @bhaugen 11:16
I'll copy this chat and make it into an issue in the agent repo, ok?

elf Pavlik @elf-pavlik 11:16
in a way a list or feed of commitments
so only commitments 'on that list' / 'in that feed' others agents consider as made by group
_
 
Feel free to add.

**Comment by bhaugen** [comment]
A little more:

Lynn Foster @fosterlynn 11:17
are you worried about people with no agent-relationship to the group saying they make a commitment?

elf Pavlik @elf-pavlik 11:17
this way group can use whatever participants agree on to manage access to that feed
well, if we consider commitment made by group, we need to have a way to verify that group plans to honor it
so we can have a way that doesn't require analyzing agent <-> agent relationships and who authored the commitment

Lynn Foster @fosterlynn 11:19
seems like this happens all the time in ecommerce, and people don't worry about it..... ?

elf Pavlik @elf-pavlik 11:19
if it appears on the list referenced by group as 'official list of our commitments' then other agents can consider it commitment of a group

Lynn Foster @fosterlynn 11:20
so Amazon website == official list of our commitments (or intents)?
but if it is in LOD, you need more?

**Comment by elf-pavlik** [comment]
relevant link by @bhaugen http://valuenetwork.referata.com/wiki/How_internal_exchanges_and_schedules_must_work_in_a_value_network

**Comment by ahdinosaur** [comment]
:+1: groups making commitments or individuals making commitments "acting as" a group.

is there an open question here?

**Comment by bhaugen** [comment]
@ahdinosaur - what's the best current reference(s) for the Scuttleverse conversation about groups?
This [ssb-group rough spec](https://git.scuttlebot.io/%25DVDzq1Da0Zupt8YQ2Z1w182DNr7HdPTJdaQv2spacNs%3D.sha256/blob/19d0cc360b528a0be056b6a01fa86caaf0198678/spec.md)?

**Comment by elf-pavlik** [comment]
I think this may work as simple as "following ones nose"

1. dereference URI denoting the group agent
2. discover location of "official list of commitments" (most likely based on very specific instance of *rdf:Property*
3. only consider commitments referenced from that list as holding for that group agent

This leaves up to the group how to handle ACL on the "official list of commitments" so anyone who can add reference of a commitment to that list can make commitments *on behalf* of the group.

**Comment by ahdinosaur** [comment]
@bhaugen 

- [latest gossip from dominic about his progress](http://viewer.scuttlebot.io/%25nEZgQY5D0EkhvbKa5hu6pRHSfSP50%2FfIlHHBj9%2Bn3BU%3D.sha256)
- [my collection of links on this topic](http://viewer.scuttlebot.io/%25hi%2FUd3rGONa%2Fx5iNLR7m%2FZL3bkrtVtmLiT11XkMziuY%3D.sha256)

**Comment by bhaugen** [comment]
@ahdinosaur - scuttlebot viewer is :wow: :clap: !

**Comment by almereyda** [comment]
We have moved the ValueFlows organization from GitHub to https://lab.allmende.io/valueflows.

This issue has been closed here, and all further discussion on this issue can be done at

> https://lab.allmende.io/valueflows/agent/-/issues/70.

If you have not done so, you are very welcome to register at https://lab.allmende.io and join the ValueFlows organization there.
