### ISSUE TITLE
Activity Pub for conversations between Agents?

### ISSUE THREAD

**Issue by bhaugen** [valueflows/agent#71]
https://hackernoon.com/mastodon-and-the-w3c-f75f376f422
https://www.w3.org/TR/activitypub/#Overview

Maybe what we should be looking at for VF conversations between Agents?

**Comment by almereyda** [comment]
We have moved the ValueFlows organization from GitHub to https://lab.allmende.io/valueflows.

This issue has been closed here, and all further discussion on this issue can be done at

> https://lab.allmende.io/valueflows/agent/-/issues/71.

If you have not done so, you are very welcome to register at https://lab.allmende.io and join the ValueFlows organization there.
